[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "python app.py"
healthcheckPath = "/api/test"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
PORT = 5001

[start]
cmd = "python app.py" 